spring:
  application:
    name: Manga list back

  # Indique à Spring de toujours initialiser la base au démarrage
  sql:
    init:
      mode: always

  # Optionnel : si tu veux que Hibernate ne tente pas de créer les tables en même temps que ton script
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties.hibernate:
      format_sql: true


  # URL de connexion : on cible 'localhost' sur le port 3306.
  # 'mangadb' est le nom de ta base.
  # 'createDatabaseIfNotExist=true' évite de devoir créer la base manuellement dans MySQL.
  datasource:
    url: jdbc:mysql://localhost:3306/mangadb?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}
